version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${SERVICE_PORT}:${SERVICE_PORT}
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD : ${DATABASE_PASSWORD}
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306