# Generated by Django 5.0.4 on 2024-06-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentModel',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('patient_id', models.CharField(max_length=64)),
                ('doctor_id', models.CharField(max_length=64)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(default='pending', max_length=64)),
                ('type', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
