# Generated by Django 5.0.4 on 2024-06-30 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointmentservice', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppointmentModel',
            new_name='Appointment',
        ),
    ]
